import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Legacy variables
        background: "var(--background)",
        foreground: "var(--foreground)",
        // Design system – Material You palette
        "surface":                    "#f8f6f5",
        "surface-bright":             "#f8f6f5",
        "surface-dim":                "#d5d4d4",
        "surface-variant":            "#dedcdc",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f2f0f0",
        "surface-container":          "#e9e8e7",
        "surface-container-high":     "#e3e2e2",
        "surface-container-highest":  "#dedcdc",
        "on-surface":                 "#2e2f2f",
        "on-surface-variant":         "#5b5b5b",
        "inverse-surface":            "#0d0e0e",
        "inverse-on-surface":         "#9d9d9c",
        "outline":                    "#777776",
        "outline-variant":            "#aeadad",
        "primary":                    "#0050d4",
        "primary-dim":                "#0046bb",
        "primary-fixed":              "#7b9cff",
        "primary-fixed-dim":          "#658eff",
        "primary-container":          "#7b9cff",
        "on-primary":                 "#f1f2ff",
        "on-primary-fixed":           "#000000",
        "on-primary-fixed-variant":   "#00266e",
        "on-primary-container":       "#001e5a",
        "inverse-primary":            "#618bff",
        "surface-tint":               "#0050d4",
        "secondary":                  "#5c5b5b",
        "secondary-dim":              "#504f4f",
        "secondary-fixed":            "#e5e2e1",
        "secondary-fixed-dim":        "#d7d4d3",
        "secondary-container":        "#e5e2e1",
        "on-secondary":               "#f5f2f1",
        "on-secondary-fixed":         "#403f3f",
        "on-secondary-fixed-variant": "#5c5b5b",
        "on-secondary-container":     "#525151",
        "tertiary":                   "#815100",
        "tertiary-dim":               "#714600",
        "tertiary-fixed":             "#f8a010",
        "tertiary-fixed-dim":         "#e79400",
        "tertiary-container":         "#f8a010",
        "on-tertiary":                "#fff0e3",
        "on-tertiary-fixed":          "#2a1700",
        "on-tertiary-fixed-variant":  "#563400",
        "on-tertiary-container":      "#4a2c00",
        "error":                      "#b31b25",
        "error-dim":                  "#9f0519",
        "error-container":            "#fb5151",
        "on-error":                   "#ffefee",
        "on-error-container":         "#570008",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body:     ["Be Vietnam Pro", "sans-serif"],
        label:    ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
